### ISSUE TITLE
Different from a same name project on SourceForge?

### ISSUE THREAD

**Issue by husy8** [lujiefsi/NPEDetector#4]
Hi there, I found a project which is discontinued has exactly the same name, NPEDetector, on [SourceForge](https://sourceforge.net/projects/npedetector/). I am wondering whether you actually enhanced it or doing something based on the original source codes, or you just start a brand new project which just has the same name with that?

**Comment by lujiefsi** [comment]
I just start a new project and really don't  know the the NPEDetector  on SourceForge. I develop this project because we find that the NPE bugs of distributed system have simple rule. The project on SourceForge maybe more complex. Thanks for reporting this odd coincidence!!! Interesting and i will  carefully study the project on SourceForge !

**Comment by husy8** [comment]
@lujiefsi Well, that's great and thank you.
